name: Update JSON
on:
    workflow_dispatch: # Manual dispatch
    push:
    schedule:
      - cron:  '5 * * * *' # Run every hour

jobs: 
  run:
    name: Update JSON
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run update bash script
      run: ./update.sh
    - name: Commit changes
      id: commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Niek
        author_email: mail@niekvandermaas.nl
        message: "Updated browser versions"
        add: "*.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}